services:
  app:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}" 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:11.4
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mariadb_data:/var/lib/mysql/
    env_file:
      - .env
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mariadb_data: