-- Category（費目）
CREATE TABLE IF NOT EXISTS `費目` (
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(20) NOT NULL,
	`notes` VARCHAR(100) DEFAULT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Transaction（家計簿）
CREATE TABLE IF NOT EXISTS `家計簿` (
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`date` DATE NOT NULL,
	`category_id` INT NOT NULL,
	`memo` VARCHAR(100) DEFAULT NULL,
	`income` INT NOT NULL DEFAULT 0,
	`expenditure` INT NOT NULL DEFAULT 0,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX (`category_id`),
	CONSTRAINT `fk_category`
		FOREIGN KEY (`category_id`) REFERENCES `費目` (`id`)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
