spring:
  application:
    name: api
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${MARIADB_DATABASE}?useSSL=false
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.api.model
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: INFO
    org.mybatis: TRACE
    com.example.api.mapper: TRACE