"""Add timestamps to CategorySQL

Revision ID: 5e1f3915e26e
Revises: 0d57c7246c9c
Create Date: 2025-06-03 06:02:21.702948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e1f3915e26e'
down_revision: Union[str, None] = '0d57c7246c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('家計簿', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('家計簿', 'income',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('家計簿', 'expenditure',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('家計簿', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('家計簿', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('費目', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('費目', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('費目', 'updated_at')
    op.drop_column('費目', 'created_at')
    op.alter_column('家計簿', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('家計簿', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('家計簿', 'expenditure',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('家計簿', 'income',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('家計簿', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
