# Generated by Django 5.2.1 on 2025-06-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=11, verbose_name='識別番号')),
                ('report_count', models.SmallIntegerField(blank=True, null=True, verbose_name='報告回数')),
                ('drug_seq', models.SmallIntegerField(verbose_name='医薬品連番')),
                ('role', models.CharField(blank=True, max_length=4, null=True, verbose_name='医薬品の関与')),
                ('drug_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='医薬品(一般名)')),
                ('product_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='医薬品(販売名)')),
                ('administration_route', models.CharField(blank=True, max_length=1024, null=True, verbose_name='投与経路')),
                ('start_date', models.CharField(blank=True, max_length=1024, null=True, verbose_name='投与開始日')),
                ('end_date', models.CharField(blank=True, max_length=1024, null=True, verbose_name='投与終了日')),
                ('dose', models.CharField(blank=True, max_length=1024, null=True, verbose_name='投与量')),
                ('dose_unit', models.CharField(blank=True, max_length=512, null=True, verbose_name='投与単位')),
                ('frequency', models.CharField(blank=True, max_length=512, null=True, verbose_name='分割投与回数')),
                ('indication', models.CharField(blank=True, max_length=768, null=True, verbose_name='使用理由')),
                ('action_taken', models.CharField(blank=True, max_length=256, null=True, verbose_name='医薬品の処置')),
                ('rechallenge', models.CharField(blank=True, max_length=1024, null=True, verbose_name='再投与による再発の有無')),
                ('risk_category', models.CharField(blank=True, max_length=256, null=True, verbose_name='リスク区分等(R3のみ)')),
                ('createby', models.CharField(blank=True, max_length=32, null=True, verbose_name='作成者')),
                ('createddate', models.DateTimeField(blank=True, null=True, verbose_name='作成日')),
                ('lastmodifiedby', models.CharField(blank=True, max_length=32, null=True, verbose_name='更新者')),
                ('lastmodifieddate', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
            ],
        ),
    ]
