# Generated by Django 5.2.1 on 2025-06-02 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImicMainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='createby',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='createddate',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='lastmodifiedby',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='lastmodifieddate',
        ),
        migrations.AddField(
            model_name='drug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
