# Generated by Django 5.2.1 on 2025-06-03 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('notes', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '費目',
                'verbose_name_plural': '費目',
                'db_table': '費目',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='メモ')),
                ('income', models.IntegerField(default=0, verbose_name='入金額')),
                ('expenditure', models.IntegerField(default=0, verbose_name='出金額')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kakeibo.category', verbose_name='費目')),
            ],
            options={
                'verbose_name': '家計簿',
                'verbose_name_plural': '家計簿',
                'db_table': '家計簿',
            },
        ),
    ]
